# Generated by Django 5.2.8 on 2025-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalosaathiapp', '0009_booking_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
